/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request;

import java.util.List;


public class EDIFACTCarAvailRuleRequest1P {

    private Uib uib;
    private Uih uih;
    private Msd msd;
    private Org org;
    private Cri cri;
    private Itm itm;
    private Pli pli;
    private Pmt pmt;
    private Rtc rtc;
    private List<Tff> tff;
    private List<Ssr> ssr;
    private List<Group1> group1;
    private List<Group4> group4;
    private Uit uit;
    private Uiz uiz;

    public Uib getUib() {
        return uib;
    }

    public EDIFACTCarAvailRuleRequest1P setUib(Uib uib) {
        this.uib = uib;  return this;
    }

    public Uih getUih() {
        return uih;
    }

    public EDIFACTCarAvailRuleRequest1P setUih(Uih uih) {
        this.uih = uih;  return this;
    }

    public Msd getMsd() {
        return msd;
    }

    public EDIFACTCarAvailRuleRequest1P setMsd(Msd msd) {
        this.msd = msd;  return this;
    }

    public Org getOrg() {
        return org;
    }

    public EDIFACTCarAvailRuleRequest1P setOrg(Org org) {
        this.org = org;  return this;
    }

    public Cri getCri() {
        return cri;
    }

    public EDIFACTCarAvailRuleRequest1P setCri(Cri cri) {
        this.cri = cri;  return this;
    }

    public Itm getItm() {
        return itm;
    }

    public EDIFACTCarAvailRuleRequest1P setItm(Itm itm) {
        this.itm = itm;  return this;
    }

    public Pli getPli() {
        return pli;
    }

    public EDIFACTCarAvailRuleRequest1P setPli(Pli pli) {
        this.pli = pli;  return this;
    }

    public Pmt getPmt() {
        return pmt;
    }

    public EDIFACTCarAvailRuleRequest1P setPmt(Pmt pmt) {
        this.pmt = pmt;  return this;
    }

    public Rtc getRtc() {
        return rtc;
    }

    public EDIFACTCarAvailRuleRequest1P setRtc(Rtc rtc) {
        this.rtc = rtc;  return this;
    }

    public List<Tff> getTff() {
        return tff;
    }

    public EDIFACTCarAvailRuleRequest1P setTff(List<Tff> tff) {
        this.tff = tff;  return this;
    }

    public List<Ssr> getSsr() {
        return ssr;
    }

    public EDIFACTCarAvailRuleRequest1P setSsr(List<Ssr> ssr) {
        this.ssr = ssr;  return this;
    }

    public List<Group1> getGroup1() {
        return group1;
    }

    public EDIFACTCarAvailRuleRequest1P setGroup1(List<Group1> group1) {
        this.group1 = group1;  return this;
    }

    public List<Group4> getGroup4() {
        return group4;
    }

    public EDIFACTCarAvailRuleRequest1P setGroup4(List<Group4> group4) {
        this.group4 = group4;  return this;
    }
    
    public Uit getUit() {
        return uit;
    }

   	public EDIFACTCarAvailRuleRequest1P setUit(Uit uit) {
        this.uit = uit;  return this;
    }

    public Uiz getUiz() {
        return uiz;
    }

    public EDIFACTCarAvailRuleRequest1P setUiz(Uiz uiz) {
        this.uiz = uiz;  return this;
    }
}