/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request;

public class Group1 {


    private Tvl tvl;
    private Prd prd;

    public Tvl getTvl() {
        return tvl;
    }

    public Group1 setTvl(Tvl tvl) {
        this.tvl = tvl;  return this;
    }

    public Prd getPrd() {
        return prd;
    }

    public Group1 setPrd(Prd prd) {
        this.prd = prd;  return this;
    }
}