/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request;

public class Group4 {

    private Rti rti;

    public Rti getRti() {
        return rti;
    }

    public Group4 setRti(Rti rti) {
        this.rti = rti;  return this;
    }
}