/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request;

import com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field.ItemNumberDetails;

public class Itm {

    private ItemNumberDetails itemNumberDetails;

    public ItemNumberDetails getItemNumberDetails() {
        return itemNumberDetails;
    }

    public Itm setItemNumberDetails(ItemNumberDetails itemNumberDetails) {
        this.itemNumberDetails = itemNumberDetails;  return this;
    }
}