/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request;

import com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field.MessageProcessingDetails;

public class Msd {

    private MessageProcessingDetails messageProcessingDetails;

    public MessageProcessingDetails getMessageProcessingDetails() {
        return messageProcessingDetails;
    }

    public Msd setMessageProcessingDetails(MessageProcessingDetails messageProcessingDetails) {
        this.messageProcessingDetails = messageProcessingDetails;  return this;
    }
}