/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request;

import com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field.DeliveringSystemDetails;
import com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field.OrgLocation;
import com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field.OriginatorDetails;
import com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field.OriginatorIdentificationDetails;

public class Org {

    private DeliveringSystemDetails deliveringSystemDetails;
    private OriginatorIdentificationDetails originatorIdentificationDetails;
    private OrgLocation orgLocation;
    private String partyName;
    private String originatorTypeCode;
    private OriginatorDetails originatorDetails;
    private String originatorsAuthorityIdentification;

    public DeliveringSystemDetails getDeliveringSystemDetails() {
        return deliveringSystemDetails;
    }

    public Org setDeliveringSystemDetails(DeliveringSystemDetails deliveringSystemDetails) {
        this.deliveringSystemDetails = deliveringSystemDetails;  return this;
    }

    public OriginatorIdentificationDetails getOriginatorIdentificationDetails() {
        return originatorIdentificationDetails;
    }

    public Org setOriginatorIdentificationDetails(OriginatorIdentificationDetails originatorIdentificationDetails) {
        this.originatorIdentificationDetails = originatorIdentificationDetails;  return this;
    }

    public OrgLocation getOrgLocation() {
        return orgLocation;
    }

    public Org setOrgLocation(OrgLocation orgLocation) {
        this.orgLocation = orgLocation;  return this;
    }

    public String getPartyName() {
        return partyName;
    }

    public Org setPartyName(String partyName) {
        this.partyName = partyName;  return this;
    }

    public String getOriginatorTypeCode() {
        return originatorTypeCode;
    }

    public Org setOriginatorTypeCode(String originatorTypeCode) {
        this.originatorTypeCode = originatorTypeCode;  return this;
    }

    public OriginatorDetails getOriginatorDetails() {
        return originatorDetails;
    }

    public Org setOriginatorDetails(OriginatorDetails originatorDetails) {
        this.originatorDetails = originatorDetails;  return this;
    }

    public String getOriginatorsAuthorityIdentification() {
        return originatorsAuthorityIdentification;
    }

    public Org setOriginatorsAuthorityIdentification(String originatorsAuthorityIdentification) {
        this.originatorsAuthorityIdentification = originatorsAuthorityIdentification;  return this;
    }
}