/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request;

import com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field.GeographicalDetails;

public class Pli extends PliBox {

    private GeographicalDetails geographicalDetails;

    public GeographicalDetails getGeographicalDetails() {
        return geographicalDetails;
    }

    public Pli setGeographicalDetails(GeographicalDetails geographicalDetails) {
        this.geographicalDetails = geographicalDetails;  return this;
    }
}