/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request;


import com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field.CreditCardInfo;
import com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field.PaymentDetails;

public class Pmt {

    private PaymentDetails paymentDetails;
    private CreditCardInfo creditCardInfo;

    public PaymentDetails getPaymentDetails() {
        return paymentDetails;
    }

    public Pmt setPaymentDetails(PaymentDetails paymentDetails) {
        this.paymentDetails = paymentDetails;  return this;
    }

    public CreditCardInfo getCreditCardInfo() {
        return creditCardInfo;
    }

    public Pmt setCreditCardInfo(CreditCardInfo creditCardInfo) {
        this.creditCardInfo = creditCardInfo;  return this;
    }
}