/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request;


import com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field.ProductIdentificationDetails;


public class Prd extends PrdBox {

    private ProductIdentificationDetails productIdentificationDetails;

    public ProductIdentificationDetails getProductIdentificationDetails() {
        return productIdentificationDetails;
    }

    public Prd setProductIdentificationDetails(ProductIdentificationDetails productIdentificationDetails) {
        this.productIdentificationDetails = productIdentificationDetails;  return this;
    }
}