/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request;

public class Rtc extends RtcBox {

    private String rateTypeIdentificationRTC;

    public String getRateTypeIdentificationRTC() {
        return rateTypeIdentificationRTC;
    }

    public Rtc setRateTypeIdentificationRTC(String rateTypeIdentificationRTC) {
        this.rateTypeIdentificationRTC = rateTypeIdentificationRTC;  return this;
    }
}