/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request;


import com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field.RateIdentificationDetails;


public class Rti {

    private RateIdentificationDetails rateIdentificationDetails;

    public RateIdentificationDetails getRateIdentificationDetails() {
        return rateIdentificationDetails;
    }

    public Rti setRateIdentificationDetails(RateIdentificationDetails rateIdentificationDetails) {
        this.rateIdentificationDetails = rateIdentificationDetails;  return this;
    }
}