/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request;

import com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field.RateInformation;
import com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field.TariffInformation;

public class Tff {

    private TariffInformation tariffInformation;
    private RateInformation rateInformation;
    private String associatedChargesInformation;

    public TariffInformation getTariffInformation() {
        return tariffInformation;
    }

    public Tff setTariffInformation(TariffInformation tariffInformation) {
        this.tariffInformation = tariffInformation;  return this;
    }

    public RateInformation getRateInformation() {
        return rateInformation;
    }

    public Tff setRateInformation(RateInformation rateInformation) {
        this.rateInformation = rateInformation;  return this;
    }

    public String getAssociatedChargesInformation() {
        return associatedChargesInformation;
    }

    public Tff setAssociatedChargesInformation(String associatedChargesInformation) {
        this.associatedChargesInformation = associatedChargesInformation;  return this;
    }
}