/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request;


import com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field.DateTimeOfInitiation;
import com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field.InteractiveMessageIdentifier;
import com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field.StatusOfTransfer;
import com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field.UihDialogueReference;

public class Uih {

    private InteractiveMessageIdentifier interactiveMessageIdentifier;
    private String interactiveMessageReferenceNumber;
    private UihDialogueReference uihDialogueReference;
    private StatusOfTransfer statusOfTransfer;
    private DateTimeOfInitiation uihDateTimeOfInitiation;

    public InteractiveMessageIdentifier getInteractiveMessageIdentifier() {
        return interactiveMessageIdentifier;
    }

    public Uih setInteractiveMessageIdentifier(InteractiveMessageIdentifier interactiveMessageIdentifier) {
        this.interactiveMessageIdentifier = interactiveMessageIdentifier;  return this;
    }

    public String getInteractiveMessageReferenceNumber() {
        return interactiveMessageReferenceNumber;
    }

    public Uih setInteractiveMessageReferenceNumber(String interactiveMessageReferenceNumber) {
        this.interactiveMessageReferenceNumber = interactiveMessageReferenceNumber;  return this;
    }

    public UihDialogueReference getUihDialogueReference() {
        return uihDialogueReference;
    }

    public Uih setUihDialogueReference(UihDialogueReference uihDialogueReference) {
        this.uihDialogueReference = uihDialogueReference;  return this;
    }

    public StatusOfTransfer getStatusOfTransfer() {
        return statusOfTransfer;
    }

    public Uih setStatusOfTransfer(StatusOfTransfer statusOfTransfer) {
        this.statusOfTransfer = statusOfTransfer;  return this;
    }

	public DateTimeOfInitiation getUihDateTimeOfInitiation() {
		return uihDateTimeOfInitiation;
	}

	public void setUihDateTimeOfInitiation(DateTimeOfInitiation uihDateTimeOfInitiation) {
		this.uihDateTimeOfInitiation = uihDateTimeOfInitiation;
	}

	

    
}