/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request;


public class Uit {

    private String interactiveMessageReferenceNumber;
    private String numberOfSegments;

    public String getInteractiveMessageReferenceNumber() {
        return interactiveMessageReferenceNumber;
    }

    public Uit setInteractiveMessageReferenceNumber(String interactiveMessageReferenceNumber) {
        this.interactiveMessageReferenceNumber = interactiveMessageReferenceNumber;  return this;
    }

    public String getNumberOfSegments() {
        return numberOfSegments;
    }

    public Uit setNumberOfSegments(String numberOfSegments) {
        this.numberOfSegments = numberOfSegments;  return this;
    }
}