/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request;

import com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field.UizDialogueReference;

public class Uiz {

    private UizDialogueReference uizDialogueReference;

    public UizDialogueReference getUizDialogueReference() {
        return uizDialogueReference;
    }

    public Uiz setUizDialogueReference(UizDialogueReference uizDialogueReference) {
        this.uizDialogueReference = uizDialogueReference;  return this;
    }
}