/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field;

public class CompanyIdentification {


    private String partyName;

    public String getPartyName() {
        return partyName;
    }

    public CompanyIdentification setPartyName(String partyName) {
        this.partyName = partyName;  return this;
    }
}