/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field;

public class CreditCardInfo {


    private String partyName;
    private String referenceNumber;
    private String date;

    public String getPartyName() {
        return partyName;
    }

    public CreditCardInfo setPartyName(String partyName) {
        this.partyName = partyName;  return this;
    }

    public String getReferenceNumber() {
        return referenceNumber;
    }

    public CreditCardInfo setReferenceNumber(String referenceNumber) {
        this.referenceNumber = referenceNumber;  return this;
    }

    public String getDate() {
        return date;
    }

    public CreditCardInfo setDate(String date) {
        this.date = date;  return this;
    }
}