/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field;

public class DateTimeOfInitiation {


    private String eventDate;
    private String eventTime;

    public String getEventDate() {
        return eventDate;
    }

    public DateTimeOfInitiation setEventDate(String eventDate) {
        this.eventDate = eventDate;  return this;
    }

    public String getEventTime() {
        return eventTime;
    }

    public DateTimeOfInitiation setEventTime(String eventTime) {
        this.eventTime = eventTime;  return this;
    }
}