/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field;

public class DeliveringSystemDetails {


    private String partyName;
    private String placeLocation;

    public String getPartyName() {
        return partyName;
    }

    public DeliveringSystemDetails setPartyName(String partyName) {
        this.partyName = partyName;  return this;
    }

    public String getPlaceLocation() {
        return placeLocation;
    }

    public DeliveringSystemDetails setPlaceLocation(String placeLocation) {
        this.placeLocation = placeLocation;  return this;
    }
}