/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field;

public class GeographicalDetails {


    private String locationQualifier;
    private String location;

    public String getLocationQualifier() {
        return locationQualifier;
    }

    public GeographicalDetails setLocationQualifier(String locationQualifier) {
        this.locationQualifier = locationQualifier;  return this;
    }

    public String getLocation() {
        return location;
    }

    public GeographicalDetails setLocation(String location) {
        this.location = location;  return this;
    }
}