/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field;

public class InterchangeRecipient {


    private String interchangeRecipientIdentification;

    public String getInterchangeRecipientIdentification() {
        return interchangeRecipientIdentification;
    }

    public InterchangeRecipient setInterchangeRecipientIdentification(String interchangeRecipientIdentification) {
        this.interchangeRecipientIdentification = interchangeRecipientIdentification;  return this;
    }
}