/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field;

public class InterchangeSender {


    private String interchangeSenderIdentification;


    public String getInterchangeSenderIdentification() {
        return interchangeSenderIdentification;
    }

    public InterchangeSender setInterchangeSenderIdentification(String interchangeSenderIdentification) {
        this.interchangeSenderIdentification = interchangeSenderIdentification;  return this;
    }
}