/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field;

public class InteractiveMessageIdentifier {


    private String messageType;
    private String messageVersionNumber;
    private String messageReleaseNumber;
    private String messageTypeSubFunctionIdentification;
    private String controllingAgency;

    public String getMessageType() {
        return messageType;
    }

    public InteractiveMessageIdentifier setMessageType(String messageType) {
        this.messageType = messageType;  return this;
    }

    public String getMessageVersionNumber() {
        return messageVersionNumber;
    }

    public InteractiveMessageIdentifier setMessageVersionNumber(String messageVersionNumber) {
        this.messageVersionNumber = messageVersionNumber;  return this;
    }

    public String getMessageReleaseNumber() {
        return messageReleaseNumber;
    }

    public InteractiveMessageIdentifier setMessageReleaseNumber(String messageReleaseNumber) {
        this.messageReleaseNumber = messageReleaseNumber;  return this;
    }

    public String getMessageTypeSubFunctionIdentification() {
        return messageTypeSubFunctionIdentification;
    }

    public InteractiveMessageIdentifier setMessageTypeSubFunctionIdentification(String messageTypeSubFunctionIdentification) {
        this.messageTypeSubFunctionIdentification = messageTypeSubFunctionIdentification;  return this;
    }

    public String getControllingAgency() {
        return controllingAgency;
    }

    public InteractiveMessageIdentifier setControllingAgency(String controllingAgency) {
        this.controllingAgency = controllingAgency;  return this;
    }
}