/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field;

public class ItemNumberDetails {


    private String itemNumber;

    public String getItemNumber() {
        return itemNumber;
    }

    public ItemNumberDetails setItemNumber(String itemNumber) {
        this.itemNumber = itemNumber;  return this;
    }
}