/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field;

public class MessageProcessingDetails {


    private String businessFunctionCode;
    private String messageFunctionCode;


    public String getBusinessFunctionCode() {
        return businessFunctionCode;
    }

    public MessageProcessingDetails setBusinessFunctionCode(String businessFunctionCode) {
        this.businessFunctionCode = businessFunctionCode;  return this;
    }

    public String getMessageFunctionCode() {
        return messageFunctionCode;
    }

    public MessageProcessingDetails setMessageFunctionCode(String messageFunctionCode) {
        this.messageFunctionCode = messageFunctionCode;  return this;
    }
}