/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field;

public class OrgLocation {


    private String placeLocationIdentification;
    private String placeLocationName;

    public String getPlaceLocationIdentification() {
        return placeLocationIdentification;
    }

    public OrgLocation setPlaceLocationIdentification(String placeLocationIdentification) {
        this.placeLocationIdentification = placeLocationIdentification;  return this;
    }

    public String getPlaceLocationName() {
        return placeLocationName;
    }

    public OrgLocation setPlaceLocationName(String placeLocationName) {
        this.placeLocationName = placeLocationName;  return this;
    }
}