/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field;

public class OriginatorDetails {


    private String countryCode;

    public String getCountryCode() {
        return countryCode;
    }

    public OriginatorDetails setCountryCode(String countryCode) {
        this.countryCode = countryCode;  return this;
    }
}