/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field;

public class OriginatorIdentificationDetails {


    private String agentIdentification1;
    private String inHouseIdentification;
    private String agentIdentification2;

   
    public String getAgentIdentification1() {
		return agentIdentification1;
	}

	public void setAgentIdentification1(String agentIdentification1) {
		this.agentIdentification1 = agentIdentification1;
	}

	public String getAgentIdentification2() {
		return agentIdentification2;
	}

	public void setAgentIdentification2(String agentIdentification2) {
		this.agentIdentification2 = agentIdentification2;
	}

	public String getInHouseIdentification() {
        return inHouseIdentification;
    }

    public OriginatorIdentificationDetails setInHouseIdentification(String inHouseIdentification) {
        this.inHouseIdentification = inHouseIdentification;  return this;
    }
}