/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field;

public class ProductDateAndTime {


    private String pickupDate;
    private String pickupTime;
    private String dropOffDate;
    private String dropOffTime;

    public String getPickupDate() {
        return pickupDate;
    }

    public ProductDateAndTime setPickupDate(String pickupDate) {
        this.pickupDate = pickupDate;  return this;
    }

    public String getPickupTime() {
        return pickupTime;
    }

    public ProductDateAndTime setPickupTime(String pickupTime) {
        this.pickupTime = pickupTime;  return this;
    }

    public String getDropOffDate() {
        return dropOffDate;
    }

    public ProductDateAndTime setDropOffDate(String dropOffDate) {
        this.dropOffDate = dropOffDate;  return this;
    }

    public String getDropOffTime() {
        return dropOffTime;
    }

    public ProductDateAndTime setDropOffTime(String dropOffTime) {
        this.dropOffTime = dropOffTime;  return this;
    }
}