/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field;

public class ProductIdentificationDetails {


    private String productIdentification;
    private String characteristicIdentification;

    public String getProductIdentification() {
        return productIdentification;
    }

    public ProductIdentificationDetails setProductIdentification(String productIdentification) {
        this.productIdentification = productIdentification;  return this;
    }

    public String getCharacteristicIdentification() {
        return characteristicIdentification;
    }

    public ProductIdentificationDetails setCharacteristicIdentification(String characteristicIdentification) {
        this.characteristicIdentification = characteristicIdentification;  return this;
    }
}