/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field;

public class RateInformation {

    private String rateTariffClassIdentification;
    private String monetaryAmount;
    private String currencyCoded;
    private String ratePlanCoded;


    public String getRateTariffClassIdentification() {
        return rateTariffClassIdentification;
    }

    public RateInformation setRateTariffClassIdentification(String rateTariffClassIdentification) {
        this.rateTariffClassIdentification = rateTariffClassIdentification;  return this;
    }

    public String getMonetaryAmount() {
        return monetaryAmount;
    }

    public RateInformation setMonetaryAmount(String monetaryAmount) {
        this.monetaryAmount = monetaryAmount;  return this;
    }

    public String getCurrencyCoded() {
        return currencyCoded;
    }

    public RateInformation setCurrencyCoded(String currencyCoded) {
        this.currencyCoded = currencyCoded;  return this;
    }

    public String getRatePlanCoded() {
        return ratePlanCoded;
    }

    public RateInformation setRatePlanCoded(String ratePlanCoded) {
        this.ratePlanCoded = ratePlanCoded;  return this;
    }
}