/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field;

public class RateIdentificationDetails {


    private String rateTariffClassIdentificationCode;

    public String getRateTariffClassIdentificationCode() {
        return rateTariffClassIdentificationCode;
    }

    public RateIdentificationDetails setRateTariffClassIdentificationCode(String rateTariffClassIdentificationCode) {
        this.rateTariffClassIdentificationCode = rateTariffClassIdentificationCode;  return this;
    }
}