/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field;


public class ReferenceIdentification {


    private String refQualifier;
    private String refNumber;
    private String partyName;

    public String getRefQualifier() {
        return refQualifier;
    }

    public ReferenceIdentification setRefQualifier(String refQualifier) {
        this.refQualifier = refQualifier;  return this;
    }

    public String getRefNumber() {
        return refNumber;
    }

    public ReferenceIdentification setRefNumber(String refNumber) {
        this.refNumber = refNumber;  return this;
    }

    public String getPartyName() {
        return partyName;
    }

    public ReferenceIdentification setPartyName(String partyName) {
        this.partyName = partyName;  return this;
    }
}