/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field;

public class SpecialRequirementTypeDetails {


    private String specialRequirementTypeIdentification;

    public String getSpecialRequirementTypeIdentification() {
        return specialRequirementTypeIdentification;
    }

    public SpecialRequirementTypeDetails setSpecialRequirementTypeIdentification(String specialRequirementTypeIdentification) {
        this.specialRequirementTypeIdentification = specialRequirementTypeIdentification;  return this;
    }
}