/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field;

public class SpecialRequirementDetails {

    private String specialRequirementDetails;

    public String getSpecialRequirementDetails() {
        return specialRequirementDetails;
    }

    public SpecialRequirementDetails setSpecialRequirementDetails(String specialRequirementDetails) {
        this.specialRequirementDetails = specialRequirementDetails;  return this;
    }
}