/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field;

public class StatusOfTransfer {


    private String senderSequenceNumber;
    private String transferPositionCode;

    public String getSenderSequenceNumber() {
        return senderSequenceNumber;
    }

    public StatusOfTransfer setSenderSequenceNumber(String senderSequenceNumber) {
        this.senderSequenceNumber = senderSequenceNumber;  return this;
    }

    public String getTransferPositionCode() {
        return transferPositionCode;
    }

    public StatusOfTransfer setTransferPositionCode(String transferPositionCode) {
        this.transferPositionCode = transferPositionCode;  return this;
    }
}