/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field;

public class SyntaxIdentifier {

    private String syntaxIdentifier;
    private String syntaxVersionNumber;

    public String getSyntaxIdentifier() {
        return syntaxIdentifier;
    }

    public SyntaxIdentifier setSyntaxIdentifier(String syntaxIdentifier) {
        this.syntaxIdentifier = syntaxIdentifier;  return this;
    }

    public String getSyntaxVersionNumber() {
        return syntaxVersionNumber;
    }

    public SyntaxIdentifier setSyntaxVersionNumber(String syntaxVersionNumber) {
        this.syntaxVersionNumber = syntaxVersionNumber;  return this;
    }
}