/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field;

public class TariffInformation {

    private String rateTypeIdentification;
    private String monetaryAmount;
    private String currencyCoded;
    private String ratePlanCoded;
    private String monetaryAmountTypeQualifier;
    private String numberOfPeriods;
    private String priceChangeIndicatorCoded;
    private String totalMonetaryAmount;
    private String dateFirst;
    private String dateSecond;
    private String specialConditionsCoded;

    public String getRateTypeIdentification() {
        return rateTypeIdentification;
    }

    public TariffInformation setRateTypeIdentification(String rateTypeIdentification) {
        this.rateTypeIdentification = rateTypeIdentification;  return this;
    }

    public String getMonetaryAmount() {
        return monetaryAmount;
    }

    public TariffInformation setMonetaryAmount(String monetaryAmount) {
        this.monetaryAmount = monetaryAmount;  return this;
    }

    public String getCurrencyCoded() {
        return currencyCoded;
    }

    public TariffInformation setCurrencyCoded(String currencyCoded) {
        this.currencyCoded = currencyCoded;  return this;
    }

    public String getRatePlanCoded() {
        return ratePlanCoded;
    }

    public TariffInformation setRatePlanCoded(String ratePlanCoded) {
        this.ratePlanCoded = ratePlanCoded;  return this;
    }

    public String getMonetaryAmountTypeQualifier() {
        return monetaryAmountTypeQualifier;
    }

    public TariffInformation setMonetaryAmountTypeQualifier(String monetaryAmountTypeQualifier) {
        this.monetaryAmountTypeQualifier = monetaryAmountTypeQualifier;  return this;
    }

    public String getNumberOfPeriods() {
        return numberOfPeriods;
    }

    public TariffInformation setNumberOfPeriods(String numberOfPeriods) {
        this.numberOfPeriods = numberOfPeriods;  return this;
    }

    public String getPriceChangeIndicatorCoded() {
        return priceChangeIndicatorCoded;
    }

    public TariffInformation setPriceChangeIndicatorCoded(String priceChangeIndicatorCoded) {
        this.priceChangeIndicatorCoded = priceChangeIndicatorCoded;  return this;
    }

    public String getTotalMonetaryAmount() {
        return totalMonetaryAmount;
    }

    public TariffInformation setTotalMonetaryAmount(String totalMonetaryAmount) {
        this.totalMonetaryAmount = totalMonetaryAmount;  return this;
    }

    public String getDateFirst() {
        return dateFirst;
    }

    public TariffInformation setDateFirst(String dateFirst) {
        this.dateFirst = dateFirst;  return this;
    }

    public String getDateSecond() {
        return dateSecond;
    }

    public TariffInformation setDateSecond(String dateSecond) {
        this.dateSecond = dateSecond;  return this;
    }

    public String getSpecialConditionsCoded() {
        return specialConditionsCoded;
    }

    public TariffInformation setSpecialConditionsCoded(String specialConditionsCoded) {
        this.specialConditionsCoded = specialConditionsCoded;  return this;
    }
}