/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field;

public class TvlLocation {

    private String placeLocation;
    private String placeLocationName;

    public String getPlaceLocation() {
        return placeLocation;
    }

    public TvlLocation setPlaceLocation(String placeLocation) {
        this.placeLocation = placeLocation;  return this;
    }

    public String getPlaceLocationName() {
        return placeLocationName;
    }

    public TvlLocation setPlaceLocationName(String placeLocationName) {
        this.placeLocationName = placeLocationName;  return this;
    }
}