/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.smookspoc.car.at.cdcp.model.edifact.availrule.onep.request.field;

public class UibDialogueReference {

    private String initiatorControlReference;

    public String getInitiatorControlReference() {
        return initiatorControlReference;
    }

    public UibDialogueReference setInitiatorControlReference(String initiatorControlReference) {
        this.initiatorControlReference = initiatorControlReference;  return this;
    }
}